---
name: Linting / Unit Tests

permissions:
  contents: read
  id-token: write

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      
jobs:
  run-unit-tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install Dependencies with NPM
        id: installation
        run: npm ci
      - name: Run Unit Tests (all projects)
        id: unittest
        run: npx turbo run test
        env:
          NODE_OPTIONS: --max-old-space-size=4096

  run-convert-e2e-tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install Dependencies with NPM
        id: installation
        run: npm ci
      - name: Configure AWS creds
        id: config-aws-creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::642712255693:role/github-actions
          role-duration-seconds: 3600
          aws-region: us-east-1
      - name: Clean up convert e2e tests
        run: cd tools/delete-stepfunctions && npm ci && npx ts-node delete-all.ts
      - name: Run convert e2e tests
        id: run-convert-e2e-tests
        run: npx turbo run test:e2e --filter=@ts2asl/convert

  run-cdk-e2e-tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install Dependencies with NPM
        id: installation
        run: npm ci
      - name: Configure AWS creds
        id: config-aws-creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::642712255693:role/github-actions
          role-duration-seconds: 3600
          aws-region: us-east-1
      - name: Run cdk e2e tests
        id: run-cdk-e2e-tests
        run: npx turbo run test:e2e --filter=cdk-tests